apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: backup-scheduled
  namespace: pg
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: homeassistant-pg
