{{ if  .Values.clusterRestore }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: homeassistant-pg
  namespace: pg
spec:
  instances: 3
  storage:
    storageClass: lvms-vg1
    size: 50Gi
  monitoring:
    enablePodMonitor: true
  enableSuperuserAccess: true
  superuserSecret:
    name: pg-superuser
  managed:
    services:
      ## disable the default services
      disabledDefaultServices: ["ro", "r"]
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: "homeassistant-pg"
              labels:
                test-label: "true"
              annotations:
                test-annotation: "true"
                metallb.universe.tf/address-pool: maraquita-ips
            spec:
              type: LoadBalancer
              loadbalancerIP: 192.168.0.129
  bootstrap:
    recovery:
      source: clusterBackup
  externalClusters:
    - name: clusterBackup
      barmanObjectStore:
        destinationPath: s3://psql-backup/
        endpointURL: http://nas.thebutlers.me:9000/
        s3Credentials:
          accessKeyId:
            name: minio
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: minio
            key: ACCESS_SECRET_KEY
        wal:
          maxParallel: 8

  backup:
    retentionPolicy: "30d"
    barmanObjectStore:
      destinationPath: s3://psql-backup/
      endpointURL: http://nas.thebutlers.me:9000/
      s3Credentials:
        accessKeyId:
          name: minio
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: minio
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
        immediateCheckpoint: true
        jobs: 2
      data:
        additionalCommandArgs:
          - "--min-chunk-size=5MB"
          - "--read-timeout=60"
          - "-vv"
---
{{ end }}
