---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: minio-eso
  namespace: pg
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: minio
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: 'secret/data/global/minio