---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: pg-superuser-eso
  namespace: pg
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: pg-superuser
    template:
      type:  kubernetes.io/basic-auth
  dataFrom:
  - extract:
      key: 'secret/data/global/pg-superuser'
# username must be postgres
# other field is password
