kind: Grafana
apiVersion: grafana.integreatly.org/v1beta1
metadata:
  labels:
    dashboards: grafana
    folders: grafana
  name: grafana
  namespace: grafana
spec:
  # deployment:
  #   spec:
  #     template:
  #       spec:
  #         containers:
  #           - name: grafana
  #             env:
  #               - name: GF_SECURITY_ADMIN_USER
  #                 valueFrom:
  #                   secretKeyRef:
  #                     key: GF_SECURITY_ADMIN_USER
  #                     name: credentials
  #               - name: GF_SECURITY_ADMIN_PASSWORD
  #                 valueFrom:
  #                   secretKeyRef:
  #                     key: GF_SECURITY_ADMIN_PASSWORD
  #                     name: credentials
  route:
    spec: {}
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
    security:
      admin_user: root
      admin_password: secret

