apiVersion: operator.victoriametrics.com/v1beta1
kind: VMScrapeConfig
metadata:
  name: external-node-exporters
  namespace: vm
spec:
  jobName: nodes
  staticConfigs:
    - targets:
        - "192.168.1.113:9100" # donnager
        - "192.168.1.207:9100" # nas
        - "192.168.1.30:9100" # lab
      labels:
        external_node: "true"
  metricsPath: /metrics
  relabelConfigs:
    - sourceLabels: [__address__]
      regex: "192.168.1.113:9100"
      targetLabel: instance
      replacement: "donnager"
      action: replace
    - sourceLabels: [__address__]
      regex: "192.168.1.207:9100"
      targetLabel: instance
      replacement: "nas"
      action: replace
    - sourceLabels: [__address__]
      regex: "192.168.1.30:9100"
      targetLabel: instance
      replacement: "lab"
      action: replace
    # For all others, set instance to the address (IP:port)
    # - sourceLabels: [__address__]
    #   targetLabel: instance
    #   action: replace
