---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata: 
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: arc-runner-pat-eso
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: arc-runner-pat
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: 'secret/data/global/arc-runner-pat'