apiVersion: v1
kind: Pod
metadata:
  name: hello-openshift
  labels:
    app: hello-openshift
spec:
  containers:
    - name: hello-openshift
      image: quay.io/openshift/origin-hello-openshift
      ports:
        - containerPort: 8888
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault


oc create secret generic github-auth --type=kubernetes.io/basic-auth \
  --from-literal=username=<your-github-username> \
  --from-literal=password=<your-github-password-or-personal-access-token> \
  -n <your-project-namespace>