apiVersion: v1
kind: Service
metadata:
  name: hello-openshift
  annotations:
    metallb.universe.tf/address-pool: maraquita-ips
spec:
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    app: hello-openshift
  type: LoadBalancer
  loadBalancerIP: 192.168.0.128