---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-secret-eso
  namespace: cert-manager
  annotations:
        argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name:  cloudflare-api-token-secret
    namespace: cert-manager
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.letsencrypt.cloudflareSecretKey }}