{{ if .Values.letsencrypt.aws }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: validated-patterns-issuer
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
spec:
  acme:
    server: {{ .Values.letsencrypt.server }}
    email: {{ .Values.letsencrypt.email }}
    privateKeySecretRef:
      name: validated-patterns-issuer-account-key
    solvers:
    - selector: {}
      dns01:
        route53:
          region: {{ .Values.letsencrypt.region }}
          accessKeyIDSecretRef:
            name: cert-manager-dns-credentials
            key: aws_access_key_id
          secretAccessKeySecretRef:
            name: cert-manager-dns-credentials
            key: aws_secret_access_key
{{- end }}
  
{{ if .Values.letsencrypt.cloudflare }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: validated-patterns-issuer
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  acme:
    server: {{ .Values.letsencrypt.server }}
    email: {{ .Values.letsencrypt.email }}
    privateKeySecretRef:
      name: validated-patterns-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: chris.butler@protonmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token

{{- end }}