{{ if or .Values.letsencrypt.aws .Values.letsencrypt.cloudflare }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lets-encrypt-certs
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
spec:
  secretName: lets-encrypt-wildcart-cert-tls
  duration: {{ .Values.letsencrypt.duration }}
  renewBefore: {{ .Values.letsencrypt.renewBefore }}
  commonName: '*.{{ $.Values.global.localClusterDomain }}'
  usages:
    {{- range .Values.letsencrypt.usages }}
    - {{ . }}
    {{- end }}
  dnsNames:
    - '*.{{ $.Values.global.localClusterDomain }}'
  issuerRef:
    name: validated-patterns-issuer
    kind: ClusterIssuer
  subject:
    organizations:
    {{- range .Values.letsencrypt.organizations }}
    - {{ . }}
    {{- end }}
{{- end }}
